
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false
fortran: false

jobs:
  include:
  - r: devel
  - r: 3.1
    warnings_are_errors: false
  - os: osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: 3.4
  - r: 3.3
  - r: 3.2
    warnings_are_errors: false
  - r: release
    env:
      - DEVEL_PACKAGES=true

matrix:
  fast_finish: true
